# track_file　を firstlabel に変更
# 参考フォーマット
# https://fastlabel.notion.site/19ea9ec20a6f48b29fa309cc8c00d2b8#527d691d8c5d45c39e82511c7078355e

import json

BASE_X = 3885.356
BASE_Y = 812.703


base_format = {
        "id": "b4bf17fa-c27e-41a4-b075-94c5ef5f139a",
        "name": "new_half_1100_1130.mp4",
        "status": "registered",
        "externalStatus": "registered",
        "url": "https://prod-fastlabel-app-annotations.s3.amazonaws.com/workspaces/bc72afdf-aab8-4623-9c64-459c1e226032/b4c460c9-d593-4946-9223-9b189465e07d/tasks/new_half_1100_1130.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAYVHKCFVVF73HR6NC%2F20241106%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Date=20241106T051522Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDmFwLW5vcnRoZWFzdC0xIkgwRgIhAPA7ZwcubJWKLrh0bfL0B1wnX2M6c91aZBVzUpOXXYW%2BAiEA%2Fhq%2BF65aNLYOmI7SVZ%2BKa93%2BZWhVs5os5lMjPSBnl%2B8qgAQIIRABGgw1OTUzNDM4NDY3NjIiDIFohkx5iUle%2FPGgJirdA2hgKhS6gIMdtgHv6tzP5SQRKsl2Au6mUE5F6IapgLzuqe%2FHcQnp1otBJxV37sdAZdj1es3HSe7k9wg5p9vmusV%2Bfm3w%2BczRSqJ6vbNE3o4dT8I3wBUcqd54cmxdafl2BEPzYX4GNSa26SzvF%2F2EpuLIzReAS%2F4h3tLgKEvwn8TdEcMFSgSZ30oVW3EwPADxAxrWll7QYoILSNGy5rXa5IlRvVYwfXEyUvt%2BxgRYYMdL0HVlu6ZlQX3CeiMdPtNLsNV5bKwvSpjZ0tWXLmXkkXCOCQ1TsVTnYpwufAj6gc5gzI5F0X5N3k50btFeu7Xm5hDJKcI7lZbdsMoNzCtZzuBPJCg%2Fpi5beChDvjR6ln%2B4By92NqfE280CvWmTVB5OXMZQ%2Fid18p7NwTqCQIZaWsLzX10e6N6X9hD%2FYmG3hLOmYj57emSdSq9tXFc9%2FRW%2FxmIFqZQG7NuWYvbkukQ9B4cZLGERfbMIhnbfNi43l2MxWp2E8UGs%2BFFr60FVv65zwFzw1iGI1JDDrkf%2B6Ly4m%2B1VYtaXvbbC3R5d9c4cWEu2T%2FGG80Kbc2WI2ykbt%2Fzf6TSr7on8zUrX60%2FWfh800aqJrCgCDdTiKX8T2l07ofxzzVI1wcso3K%2FkiC7XETCc5qq5BjqkAS8RRnLD%2Bnz51VRcuZWTta8%2FihNuUmc3PnRIy5JAZFSdvacNqmKSO145OssZBWhI04cmN5GIfNOaMfFsIzUETGdkNFFRNnt61jcRo%2B9gr8y7xF6TosphUIAo5WskAJtFITm43FrVkpw5RYkCgTPTwjqcLq9kJKzoaKUroBfoqLySHKeWCj6bHlfkZaOgO%2BLWmMyJHeQ7WUEezTktUwY09kRnThBk&X-Amz-Signature=cdd231bf106a06ae882389abc9e57160d84af318eaf346ab35d5f510a2008793",
        "width": 3932,
        "height": 2312,
        "fps": 30,
        "frameCount": 4498,
        "duration": 149.9333333333,
        "secondsToAnnotate": 0,
        "annotations": [
            {
                "type": "bbox",
                "title": "worker",
                "value": "worker",
                "color": "#D10069",
                "attributes": [],
                "points": {
                    "1": {           # number of frame
                        "value": [
                            271.63,  # top-left x point
                            130.96,  # top-left y point
                            755.36,  # bottom-right x point
                            470.29   # bottom-right y point
                        ],
                    }
                }
            }
        ],
        "tags": [],
    }

def load_json_file(file):
    with open(file, 'r') as f:
        workers = json.load(f)

    return workers

def convert_fastlabel(track_json):

    annon = []

    track_ids = {}

    for frame in track_json:
        if frame['frame_id'] >= 4498*2: #　まずは前半30分
            break
        if frame['frame_id'] % 2 == 1:
            continue
        frame_id = frame['frame_id'] // 2
        print("Frame_id: ", frame_id)
        for track in frame['tracks']:
            tid = track['track_id']
            if tid in track_ids:
                track_ids[tid][str(frame_id+1)]={
                    "value":[
                        track['bbox'][0]-BASE_X,
                        track['bbox'][1]-BASE_Y,
                        track['bbox'][2]+track['bbox'][0]-BASE_X,
                        track['bbox'][3]+track['bbox'][1]-BASE_Y
                    ],
                    "autogenerated": False
                }
            else:
                track_ids[tid] = {
                    str(frame_id+1): {
                        "value": [
                            track['bbox'][0]-BASE_X,
                            track['bbox'][1]-BASE_Y,
                            track['bbox'][2]+track['bbox'][0]-BASE_X,
                            track['bbox'][3]+track['bbox'][1]-BASE_Y
                        ],
                        "autogenerated": False
                    }
                }
    
    new_frame = base_format
#    print(track_ids)

    annon = []
    for tid,v in track_ids.items():        
        annon.append({
            "type": "bbox",
            "title": "worker",
            "value": "worker",
            "color": "#D10069",
            "attributes": [],
            "points": v
            
        })

    new_frame['annotations'] = annon

    return new_frame

if __name__ == '__main__':
#    workers = load_json_file("adjusted_tracking_result_2024-10-03_39600_43200_200_99_90_True_150_200_200_9990_10_True_90.json")
    workers = load_json_file("modify_adjusted_tracking_result_2024-10-03_39600_43200_200_99_90_True_150_200_200_9985_10_True_90.json")

    new_frame = convert_fastlabel(workers)

    with open('fastlabel_upload.json', 'w') as f:
        json.dump([new_frame], f, indent=4)
